project:
  type: book

book:
  title: "Bfh-ai-compendium"
  author: "Norah Jones"
  date: "02/11/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



